import random 
def dice_rolling():
    dice = range(1,7)


    roll_dice1 = random.choice(dice)
    roll_dice2 = random.choice(dice)

    print(f"\nThe number generated by first dice is \033[1;3m{roll_dice1}\033[0m")
    print(f"\nThe number generated by second dice is \033[1;3m{roll_dice2}\033[0m")

    total_number = roll_dice1 + roll_dice2
    print(f"\nThe total number generated by both dice is \033[1;3m{total_number}\033[0m")

if __name__ == "__main__":
    dice_rolling()